version: '3.1'

services:
   db:
      image: mariadb
      container_name: mpb_prof
      restart: always
      ports:
       - '6601:3306'
      environment:
         - MYSQL_ROOT_PASSWORD=test
      volumes:
          - ./database:/var/lib/mysql